#pragma once

#include <OpenNI.h>
#include <iostream>
#include <sstream>
#include <cstdio>

enum
{
    // Camera
    LIPS_STREAM_PROPERTY_FOCAL_LENGTH_X      = 200,
    LIPS_STREAM_PROPERTY_FOCAL_LENGTH_Y      = 201,
    LIPS_STREAM_PROPERTY_PRINCIPAL_POINT_X   = 202,
    LIPS_STREAM_PROPERTY_PRINCIPAL_POINT_Y   = 203,
    LIPS_STREAM_PROPERTY_FOCAL_LENGTH_R      = 205,
    LIPS_STREAM_PROPERTY_FOCAL_LENGTH_L      = 206,
    LIPS_STREAM_PROPERTY_PRINCIPAL_POINT_X_R = 207,
    LIPS_STREAM_PROPERTY_PRINCIPAL_POINT_Y_R = 208,
    LIPS_STREAM_PROPERTY_PRINCIPAL_POINT_X_L = 209,
    LIPS_STREAM_PROPERTY_PRINCIPAL_POINT_Y_L = 210,
    LIPS_STREAM_PROPERTY_FOCAL_LENGTH_X_R    = 211,
    LIPS_STREAM_PROPERTY_FOCAL_LENGTH_Y_R    = 212,
    LIPS_STREAM_PROPERTY_FOCAL_LENGTH_X_L    = 213,
    LIPS_STREAM_PROPERTY_FOCAL_LENGTH_Y_L    = 214,
};
